### ISSUE TITLE
Move chemical libraries from the user's home directory to the application data folder

### ISSUE THREAD

**Issue by khbrassel** [eawag-surface-waters-research/ChemEQL#1]
Currently, the binary libraries CQLJ.SolidsLib and CQLJ.RegularLib are stored simply in the user home directory. A better place would be the user specific application data directory as supported by the respective OS:
- MAC OSX: ~/Library/Application Support/ChemEQL 
- Windows: ~/AppData/Roaming/ChemEQL
- Linux: ~/.chemeql

Shall we do so?

**Comment by BeatMueller** [comment]
Hallo Kai
Ja, da bin ich sehr einverstanden!
Gruss
Beat

**Comment by khbrassel** [comment]
Resolved with commit 4d7c47ec05
